"use client";

import { useEffect, useState } from "react";

type Status = { task:string;phase:string;status:string;steps:string[];currentStep:number;lastAction:string;commit:string;startedAt:string|null;updatedAt:string|null;machine:string };
type RoadmapItem={order:number;id:string|null;title:string|null;outcome:string|null;status:"active"|"queued"|"blocked"|"completed"};
type Autonomous = { enabled:boolean;cycle:number;status:string;focus:string|null;lastResult:string|null;startedAt:string|null;updatedAt:string|null;heartbeatAt:string|null;heartbeatHealthy:boolean;consecutiveFailures:number;automaticRecoveries:number;recoveredFromCycle:number|null;recoveryState:string;nextRetryAt:string|null;roadmap:RoadmapItem[];events:{type:string;text:string;exitCode:number|null}[];reports:{id:string;createdAt:string;text:string|null}[] };

const recoveryCopy={
  "tr-TR":{title:"Otomasyon kurtarma",healthy:"Heartbeat sağlıklı",stale:"Heartbeat gecikmiş",failures:"Ardışık hata",recoveries:"Otomatik kurtarma",retry:"Sonraki güvenli deneme",ready:"Bekleme yok · hazır"},
  "en-US":{title:"Automation recovery",healthy:"Heartbeat healthy",stale:"Heartbeat delayed",failures:"Consecutive failures",recoveries:"Automatic recoveries",retry:"Next safe retry",ready:"No backoff · ready"},
  "de-DE":{title:"Automatische Wiederherstellung",healthy:"Heartbeat gesund",stale:"Heartbeat verzögert",failures:"Fehler in Folge",recoveries:"Automatische Wiederherstellungen",retry:"Nächster sicherer Versuch",ready:"Keine Wartezeit · bereit"},
  "fr-FR":{title:"Récupération automatique",healthy:"Heartbeat sain",stale:"Heartbeat retardé",failures:"Échecs consécutifs",recoveries:"Récupérations automatiques",retry:"Prochaine tentative sûre",ready:"Aucun délai · prêt"},
} as const;

const roadmapCopy={
  "tr-TR":{title:"Sıradaki geliştirmeler",intro:"Otonom sistem en az 10 gelecek ürün fazını sürekli güncel tutar.",active:"Şimdi",queued:"Sırada",blocked:"Engelli",completed:"Tamamlandı"},
  "en-US":{title:"Upcoming improvements",intro:"The autonomous system continuously maintains at least 10 future product phases.",active:"Now",queued:"Queued",blocked:"Blocked",completed:"Completed"},
  "de-DE":{title:"Nächste Verbesserungen",intro:"Das autonome System plant laufend mindestens 10 zukünftige Produktphasen.",active:"Jetzt",queued:"Geplant",blocked:"Blockiert",completed:"Erledigt"},
  "fr-FR":{title:"Améliorations à venir",intro:"Le système autonome maintient en permanence au moins 10 phases futures.",active:"Maintenant",queued:"À venir",blocked:"Bloqué",completed:"Terminé"},
} as const;

export function DevelopmentLive({initial,locale}:{initial:Status;locale:keyof typeof recoveryCopy}) {
  const [data,setData]=useState(initial),[autonomous,setAutonomous]=useState<Autonomous|null>(null);
  const [connected,setConnected]=useState(true),[modeBusy,setModeBusy]=useState(false),[modeError,setModeError]=useState("");
  async function refresh(){try{const[statusResponse,autonomousResponse]=await Promise.all([fetch("/api/admin/development/status",{cache:"no-store"}),fetch("/api/admin/development/autonomous",{cache:"no-store"})]);if(!statusResponse.ok||!autonomousResponse.ok)throw new Error();const[next,nextAutonomous]=await Promise.all([statusResponse.json()as Promise<Status>,autonomousResponse.json()as Promise<Autonomous>]);setData(next);setAutonomous(nextAutonomous);setConnected(true)}catch{setConnected(false)}}
  useEffect(()=>{const initialTimer=window.setTimeout(()=>void refresh(),0),timer=window.setInterval(()=>void refresh(),3000);return()=>{window.clearTimeout(initialTimer);window.clearInterval(timer)}},[]);
  async function changeMode(enabled:boolean){if(modeBusy)return;setModeBusy(true);setModeError("");try{const csrf=await fetch("/api/admin/auth/csrf",{cache:"no-store"}),{token}=await csrf.json()as{token:string};const response=await fetch("/api/admin/development/autonomous/mode",{method:"POST",headers:{"content-type":"application/json","x-csrf-token":token},body:JSON.stringify({enabled})});if(!response.ok)throw new Error("Otonom sistem durumu değiştirilemedi.");setAutonomous(value=>value?{...value,enabled,status:enabled?"Queued":"Stopping"}:value);window.dispatchEvent(new CustomEvent("boecl-autonomous-mode",{detail:{enabled}}));await refresh()}catch(error){setModeError(error instanceof Error?error.message:"Beklenmeyen hata.")}finally{setModeBusy(false)}}
  const percent=data.steps.length?Math.round(Math.min(data.currentStep,data.steps.length)/data.steps.length*100):0;
  const recovery=recoveryCopy[locale];
  const roadmapText=roadmapCopy[locale];
  return <div className="development-live">
    <section className="admin-panel development-hero"><header><div><p className="section-kicker">CODEX CANLI</p><h2>{data.task}</h2></div><span className={`development-state state-${data.status.toLowerCase()}`}><i/>{data.status}</span></header><p>{data.phase}</p><div className="automation-progress" role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={percent}><span style={{width:`${percent}%`}}/></div><footer><strong>%{percent}</strong><span>{connected?"3 saniyede bir canlı yenileniyor":"Bağlantı bekleniyor"}</span></footer></section>
    {autonomous&&<section className="admin-panel development-detail"><header><div><p className="section-kicker">OTONOM AI YÖNETİMİ</p><h2>Çevrim {autonomous.cycle}</h2></div><button type="button" disabled={modeBusy} onClick={()=>void changeMode(!autonomous.enabled)}>{modeBusy?"İşleniyor…":autonomous.enabled?"Otonom sistemi durdur":"Otonom sistemi başlat"}</button></header><p>{autonomous.focus||"Sonraki çevrim bekleniyor."}</p>{modeError&&<p role="alert">{modeError}</p>}<dl><div><dt>Otonom mod</dt><dd>{autonomous.enabled?"Açık · diğer admin modülleri kilitli":"Kapalı · admin modülleri açık"}</dd></div><div><dt>Durum</dt><dd>{autonomous.status}</dd></div><div><dt>Son sonuç</dt><dd>{autonomous.lastResult||"—"}</dd></div></dl></section>}
    {autonomous&&<section className={`admin-panel development-recovery ${autonomous.heartbeatHealthy?"is-healthy":"is-risk"}`}><header><div><p className="section-kicker">{recovery.title}</p><h2>{autonomous.heartbeatHealthy?recovery.healthy:recovery.stale}</h2></div><span className="recovery-pulse" aria-hidden/></header><div className="recovery-metrics"><article><strong>{autonomous.consecutiveFailures}</strong><span>{recovery.failures}</span></article><article><strong>{autonomous.automaticRecoveries}</strong><span>{recovery.recoveries}</span></article></div><dl><div><dt>{recovery.retry}</dt><dd>{autonomous.nextRetryAt?new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeStyle:"medium"}).format(new Date(autonomous.nextRetryAt)):recovery.ready}</dd></div><div><dt>Heartbeat</dt><dd>{autonomous.heartbeatAt?new Intl.DateTimeFormat(locale,{timeStyle:"medium"}).format(new Date(autonomous.heartbeatAt)):"—"}</dd></div></dl></section>}
    {autonomous&&autonomous.roadmap.length>0&&<section className="admin-panel development-roadmap"><header><div><p className="section-kicker">OTONOM YOL HARİTASI</p><h2>{roadmapText.title}</h2></div><strong>{autonomous.roadmap.filter(item=>item.status!=="completed").length}</strong></header><p>{roadmapText.intro}</p><ol>{autonomous.roadmap.map(item=><li className={`roadmap-${item.status}`} key={item.id??item.order}><span>{item.order}</span><div><header><h3>{item.title}</h3><small>{roadmapText[item.status]}</small></header><p>{item.outcome}</p></div></li>)}</ol></section>}
    <section className="admin-panel development-steps"><h2>Faz adımları</h2><ol>{data.steps.map((step,index)=><li className={index<data.currentStep?"done":index===data.currentStep?"current":""} key={`${index}-${step}`}><span>{index<data.currentStep?"✓":index+1}</span><p>{step}</p></li>)}</ol></section>
    <section className="admin-panel development-detail"><h2>Son işlem</h2><p>{data.lastAction||"—"}</p><dl><div><dt>Faz</dt><dd>{data.phase}</dd></div><div><dt>Commit</dt><dd>{data.commit||"Henüz yok"}</dd></div><div><dt>Makine</dt><dd>{data.machine}</dd></div><div><dt>Güncelleme</dt><dd>{data.updatedAt?new Intl.DateTimeFormat("tr-TR",{dateStyle:"medium",timeStyle:"medium"}).format(new Date(data.updatedAt)):"—"}</dd></div></dl></section>
    {autonomous&&<section className="admin-panel development-detail"><p className="section-kicker">CANLI OPERASYON AKIŞI</p><h2>Codex ne yapıyor?</h2><div className="automation-report-document">{autonomous.events.length===0?<p>Yeni olay bekleniyor.</p>:autonomous.events.slice(-30).reverse().map((event,index)=><article key={`${index}-${event.type}`}><strong>{event.type==="message"?"AI":event.type==="command_started"?"Komut başladı":event.type==="command_completed"?`Komut tamamlandı${event.exitCode===null?"":` (${event.exitCode})`}`:"Çevrim"}</strong><pre>{event.text}</pre></article>)}</div></section>}
    {autonomous&&autonomous.reports.length>0&&<section className="admin-panel development-detail"><p className="section-kicker">ÇEVRİM RAPORLARI</p><h2>Son tamamlanan işler</h2>{autonomous.reports.map(report=><details key={report.id}><summary>{new Intl.DateTimeFormat("tr-TR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(report.createdAt))}</summary><pre>{report.text||"Rapor metni bulunmuyor."}</pre></details>)}</section>}
  </div>;
}
