"use client";

import { useEffect, useState } from "react";

type Status = { task:string; phase:string; status:string; steps:string[]; currentStep:number; lastAction:string; commit:string; startedAt:string|null; updatedAt:string|null; machine:string };
type Autonomous = { enabled:boolean; cycle:number; status:string; focus:string|null; lastResult:string|null; startedAt:string|null; updatedAt:string|null; events:{type:string;text:string;exitCode:number|null}[]; reports:{id:string;createdAt:string;text:string|null}[] };

export function DevelopmentLive({initial}:{initial:Status}) {
  const [data,setData]=useState(initial);
  const [autonomous,setAutonomous]=useState<Autonomous|null>(null);
  const [connected,setConnected]=useState(true);
  useEffect(()=>{let active=true;const refresh=async()=>{try{const[statusResponse,autonomousResponse]=await Promise.all([fetch("/api/admin/development/status",{cache:"no-store"}),fetch("/api/admin/development/autonomous",{cache:"no-store"})]);if(!statusResponse.ok||!autonomousResponse.ok)throw new Error();const[next,nextAutonomous]=await Promise.all([statusResponse.json() as Promise<Status>,autonomousResponse.json() as Promise<Autonomous>]);if(active){setData(next);setAutonomous(nextAutonomous);setConnected(true)}}catch{if(active)setConnected(false)}};void refresh();const timer=window.setInterval(()=>void refresh(),3000);return()=>{active=false;window.clearInterval(timer)}},[]);
  const percent=data.steps.length?Math.round(Math.min(data.currentStep,data.steps.length)/data.steps.length*100):0;
  return <div className="development-live">
    <section className="admin-panel development-hero"><header><div><p className="section-kicker">CODEX CANLI</p><h2>{data.task}</h2></div><span className={`development-state state-${data.status.toLowerCase()}`}><i/>{data.status}</span></header><p>{data.phase}</p><div className="automation-progress" role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={percent}><span style={{width:`${percent}%`}}/></div><footer><strong>%{percent}</strong><span>{connected?"3 saniyede bir canlı yenileniyor":"Bağlantı bekleniyor"}</span></footer></section>
    <section className="admin-panel development-steps"><h2>Faz adımları</h2><ol>{data.steps.map((step,index)=><li className={index<data.currentStep?"done":index===data.currentStep?"current":""} key={`${index}-${step}`}><span>{index<data.currentStep?"✓":index+1}</span><p>{step}</p></li>)}</ol></section>
    <section className="admin-panel development-detail"><h2>Son işlem</h2><p>{data.lastAction||"—"}</p><dl><div><dt>Faz</dt><dd>{data.phase}</dd></div><div><dt>Commit</dt><dd>{data.commit||"Henüz yok"}</dd></div><div><dt>Makine</dt><dd>{data.machine}</dd></div><div><dt>Güncelleme</dt><dd>{data.updatedAt?new Intl.DateTimeFormat("tr-TR",{dateStyle:"medium",timeStyle:"medium"}).format(new Date(data.updatedAt)):"—"}</dd></div></dl></section>
    {autonomous&&<section className="admin-panel development-detail"><header><div><p className="section-kicker">OTONOM AI YÖNETİMİ</p><h2>Çevrim {autonomous.cycle}</h2></div><span className={`development-state state-${autonomous.status.toLowerCase()}`}><i/>{autonomous.enabled?autonomous.status:"Kapalı"}</span></header><p>{autonomous.focus||"Sonraki çevrim bekleniyor."}</p><dl><div><dt>Otonom mod</dt><dd>{autonomous.enabled?"Açık":"Kapalı"}</dd></div><div><dt>Son sonuç</dt><dd>{autonomous.lastResult||"—"}</dd></div><div><dt>Güncelleme</dt><dd>{autonomous.updatedAt?new Intl.DateTimeFormat("tr-TR",{dateStyle:"medium",timeStyle:"medium"}).format(new Date(autonomous.updatedAt)):"—"}</dd></div></dl></section>}
    {autonomous&&<section className="admin-panel development-detail"><p className="section-kicker">CANLI OPERASYON AKIŞI</p><h2>Codex ne yapıyor?</h2><div className="automation-report-document">{autonomous.events.length===0?<p>Yeni olay bekleniyor.</p>:autonomous.events.slice(-30).reverse().map((event,index)=><article key={`${index}-${event.type}`}><strong>{event.type==="message"?"AI":event.type==="command_started"?"Komut başladı":event.type==="command_completed"?`Komut tamamlandı${event.exitCode===null?"":` (${event.exitCode})`}`:"Çevrim"}</strong><pre>{event.text}</pre></article>)}</div></section>}
    {autonomous&&autonomous.reports.length>0&&<section className="admin-panel development-detail"><p className="section-kicker">ÇEVRİM RAPORLARI</p><h2>Son tamamlanan işler</h2>{autonomous.reports.map(report=><details key={report.id}><summary>{new Intl.DateTimeFormat("tr-TR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(report.createdAt))}</summary><pre>{report.text||"Rapor metni bulunmuyor."}</pre></details>)}</section>}
  </div>;
}
