"use client";
import {FormEvent,useState}from"react";
import {useRouter}from"next/navigation";
import type{MediaItem,SupportingLibrary}from"@/lib/admin-api";

type Copy=Record<string,string>;
export function LibraryManager({library,media,copy}:{library:SupportingLibrary;media:MediaItem[];copy:Copy}){
  const router=useRouter();const[message,setMessage]=useState("");
  async function token(){const response=await fetch("/api/admin/auth/csrf",{cache:"no-store"});return((await response.json())as{token:string}).token}
  async function submit(event:FormEvent<HTMLFormElement>,path:string){event.preventDefault();setMessage("");try{const form=event.currentTarget,data=new FormData(form);const response=await fetch(`/api/admin/supporting/${path}`,{method:"POST",headers:{"content-type":"application/json","x-csrf-token":await token()},body:JSON.stringify(Object.fromEntries(data.entries()))});if(!response.ok)throw new Error();form.reset();setMessage(copy.success);router.refresh()}catch{setMessage(copy.error)}}
  async function upload(event:FormEvent<HTMLFormElement>){event.preventDefault();setMessage("");try{const form=event.currentTarget,response=await fetch("/api/admin/media/",{method:"POST",headers:{"x-csrf-token":await token()},body:new FormData(form)});if(!response.ok)throw new Error();form.reset();setMessage(copy.success);router.refresh()}catch{setMessage(copy.error)}}
  async function deleteUnused(id:string){setMessage("");try{const response=await fetch(`/api/admin/media/${id}/delete-unused`,{method:"POST",headers:{"x-csrf-token":await token()}});if(!response.ok)throw new Error();setMessage(copy.success);router.refresh()}catch{setMessage(copy.error)}}
  const localized=(path:string,label:string)=><form className="admin-form compact-form" onSubmit={event=>submit(event,path)}><h2>{label}</h2><label>{copy.locale}<select name="locale" defaultValue="tr-TR"><option>tr-TR</option><option>en-US</option><option>de-DE</option></select></label><label>{copy.slug}<input name="slug" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*"/></label><label>{copy.name}<input name="name" required maxLength={160}/></label><button>{copy.add}</button></form>;
  const list=(items:{id:string;name?:string;displayName?:string;slug?:string;locale?:string;url?:string}[])=>items.length?<ul className="library-list">{items.map(item=><li key={item.id}><strong>{item.name??item.displayName}</strong><small>{[item.locale,item.slug,item.url].filter(Boolean).join(" · ")}</small></li>)}</ul>:<p className="muted">{copy.empty}</p>;
  return <><div className="library-grid">{localized("categories",copy.category)}{localized("tags",copy.tag)}<form className="admin-form compact-form" onSubmit={event=>submit(event,"authors")}><h2>{copy.author}</h2><label>{copy.slug}<input name="slug" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*"/></label><label>{copy.name}<input name="name" required/></label><button>{copy.add}</button></form><form className="admin-form compact-form" onSubmit={event=>submit(event,"sources")}><h2>{copy.source}</h2><label>{copy.name}<input name="name" required/></label><label>{copy.url}<input name="url" type="url" required/></label><button>{copy.add}</button></form></div><div className="library-grid"><section className="admin-panel"><h2>{copy.category}</h2>{list(library.categories)}</section><section className="admin-panel"><h2>{copy.tag}</h2>{list(library.tags)}</section><section className="admin-panel"><h2>{copy.author}</h2>{list(library.authors)}</section><section className="admin-panel"><h2>{copy.source}</h2>{list(library.sources)}</section></div><section className="admin-panel media-panel"><form className="admin-form compact-form" onSubmit={upload}><h2>{copy.media}</h2><label>{copy.file}<input name="file" type="file" accept="image/jpeg,image/png,image/webp" required/></label><button>{copy.upload}</button></form>{media.length?<ul className="library-list media-list">{media.map(item=><li key={item.id}><strong>{item.fileName}</strong><small>{item.contentType} · {(item.byteLength/1024).toFixed(1)} KB{item.width&&item.height?` · ${item.width}×${item.height}`:""}{item.optimizedByteLength?` · ${copy.optimized}: ${(item.optimizedByteLength/1024).toFixed(1)} KB`:""} · {copy.usage}: {item.usageCount}</small>{item.canDelete&&<button className="button-secondary" onClick={()=>deleteUnused(item.id)}>{copy.deleteUnused}</button>}</li>)}</ul>:<p className="muted">{copy.empty}</p>}</section>{message&&<p className="admin-message" role="status">{message}</p>}</>;
}
