"use client";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import type { Locale } from "@/i18n/config";

type VisualTask={id:string;status:string;sectionContext:string;visualPurpose:string;proposedPrompt:string;negativePrompt:string;attemptCount:number;reviewerNote:string|null;updatedAt:string};
export type VisualQualityReport={checkedAt:string;total:number;passing:number;needsReview:number;missingCover:number;textRisk:number;averageScore:number;queued:number;approved:number;items:{id:string;locale:string;slug:string;title:string;publishedAt:string|null;score:number;grade:string;risks:string[];bodyImageCount:number;coverUrl:string|null;coverAltText:string|null;width:number|null;height:number|null;optimizedBytes:number|null;visualTask:VisualTask|null}[]};

const base={coverMissing:"Missing cover",altMissing:"Missing alt text",topicMismatch:"Weak topic match",textRisk:"Text / logo risk",cropRisk:"Mobile crop risk",notOptimized:"Not optimized",oversized:"Oversized file",rightsMissing:"Missing rights metadata",bodyMissing:"Missing body visual",dimensionsUnknown:"Unknown dimensions",clean:"All automated gates clear",body:"body visuals",sync:"Queue risky stories",syncing:"Preparing queue…",context:"Section context",brief:"Original text-free design brief",negative:"Exclude from output",reviewAction:"Start review",approve:"Approve brief",reject:"Reject",retry:"Request new brief",note:"Editorial decision note",queued:"Persistent queue",approved:"Approved"};
const copy={
  "tr-TR":{...base,eyebrow:"GÖRSEL ÜRETİM SERVİSİ",title:"Görsel Yenileme Stüdyosu",lead:"Her makaleyi tam metin ve bölüm bağlamıyla; konu eşleşmesi, yazısız tasarım, mobil kırpma, performans ve kullanım hakkı kapılarında tarar.",total:"Yayındaki makale",passing:"Kapıdan geçen",review:"İnceleme gerektiren",average:"Ortalama kalite",queue:"Öncelikli görsel kuyruğu",queueLead:"Her riskli kayıt tam metinden üretilmiş somut bir brief ile incelenir; sağlam görsel otomatik değiştirilmez.",open:"Makaleyi aç",edit:"Editörde incele",coverMissing:"Kapak eksik",altMissing:"Alt metin eksik",topicMismatch:"Konu eşleşmesi zayıf",textRisk:"Yazı / logo riski",cropRisk:"Mobil kırpma riski",notOptimized:"Optimize edilmemiş",oversized:"Dosya büyük",rightsMissing:"Kaynak / hak bilgisi eksik",bodyMissing:"Gövde görseli eksik",dimensionsUnknown:"Boyut bilinmiyor",clean:"Tüm otomatik kapılar temiz",body:"gövde görseli",sync:"Riskli makaleleri kuyruğa al",syncing:"Kuyruk hazırlanıyor…",context:"Bölüm bağlamı",brief:"Yazısız özgün tasarım briefi",negative:"Üretimden dışla",reviewAction:"İncelemeye al",approve:"Briefi onayla",reject:"Reddet",retry:"Yeni brief iste",note:"Editoryal karar notu",queued:"Kalıcı kuyruk",approved:"Onaylanan"},
  "en-US":{...base,eyebrow:"VISUAL GENERATION SERVICE",title:"Visual Renewal Studio",lead:"Audits every story using its full text and section context for topic fit, text-free design, mobile crop, performance, and rights.",total:"Published stories",passing:"Passing",review:"Needs review",average:"Average quality",queue:"Priority visual queue",queueLead:"Every risky story gets a concrete full-text brief; healthy visuals are never replaced automatically.",open:"Open story",edit:"Review in editor"},
  "de-DE":{...base,eyebrow:"BILDERZEUGUNGSDIENST",title:"Studio für Bilderneuerung",lead:"Prüft Beiträge mit Volltext und Abschnittskontext auf Themenbezug, textfreie Gestaltung, mobilen Beschnitt, Leistung und Rechte.",total:"Veröffentlichte Beiträge",passing:"Bestanden",review:"Zu prüfen",average:"Durchschnitt",queue:"Priorisierte Bildwarteschlange",queueLead:"Jeder riskante Beitrag erhält ein konkretes Briefing; gute Bilder werden nie automatisch ersetzt.",open:"Beitrag öffnen",edit:"Im Editor prüfen",sync:"Riskante Beiträge einreihen",syncing:"Warteschlange wird erstellt…",context:"Abschnittskontext",brief:"Originales textfreies Bildbriefing",negative:"Vom Ergebnis ausschließen",reviewAction:"Prüfung beginnen",approve:"Briefing freigeben",reject:"Ablehnen",retry:"Neues Briefing anfordern",note:"Redaktionelle Entscheidungsnotiz",queued:"Dauerhafte Warteschlange",approved:"Freigegeben"},
  "fr-FR":{...base,eyebrow:"SERVICE DE GÉNÉRATION VISUELLE",title:"Studio de renouvellement visuel",lead:"Contrôle chaque article avec son texte intégral et sa section : pertinence, création sans texte, recadrage mobile, performance et droits.",total:"Articles publiés",passing:"Conformes",review:"À vérifier",average:"Qualité moyenne",queue:"File visuelle prioritaire",queueLead:"Chaque article à risque reçoit un brief concret ; une image saine n’est jamais remplacée automatiquement.",open:"Ouvrir l’article",edit:"Vérifier dans l’éditeur",sync:"Mettre les articles à risque en file",syncing:"Préparation de la file…",context:"Contexte de section",brief:"Brief visuel original sans texte",negative:"Exclure du résultat",reviewAction:"Commencer la vérification",approve:"Approuver le brief",reject:"Rejeter",retry:"Demander un nouveau brief",note:"Note de décision éditoriale",queued:"File persistante",approved:"Approuvés"}
} satisfies Record<Locale,Record<string,string>>;

export function VisualQualityDesk({locale,report}:{locale:Locale;report:VisualQualityReport}){
  const c=copy[locale],router=useRouter(),[busy,setBusy]=useState(""),[message,setMessage]=useState("");
  const labels:Record<string,string>={"missing-cover":c.coverMissing,"missing-alt":c.altMissing,"topic-mismatch":c.topicMismatch,"text-risk":c.textRisk,"unsafe-crop":c.cropRisk,"not-optimized":c.notOptimized,oversized:c.oversized,"missing-rights":c.rightsMissing,"missing-body-visual":c.bodyMissing,"unknown-dimensions":c.dimensionsUnknown};
  async function send(path:string,note?:string){setBusy(path);setMessage("");try{const csrf=await fetch("/api/admin/auth/csrf",{cache:"no-store"}),{token}=await csrf.json()as{token:string};const response=await fetch(`/api/admin/automation/visual-quality/${path}`,{method:"POST",headers:{"content-type":"application/json","x-csrf-token":token},body:JSON.stringify({note})});if(!response.ok)throw new Error();setMessage("✓");router.refresh()}catch{setMessage("Action failed")}finally{setBusy("")}}
  return <>
    <header className="visual-desk-hero"><div><p className="section-kicker">{c.eyebrow}</p><h1>{c.title}</h1><p>{c.lead}</p><button type="button" disabled={Boolean(busy)} onClick={()=>void send("queue")}>{busy==="queue"?c.syncing:c.sync}</button>{message&&<span role="status">{message}</span>}</div><div className="visual-score-dial" aria-label={`${c.average}: ${report.averageScore}`}><strong>{report.averageScore}</strong><span>/ 100</span></div></header>
    <section className="visual-quality-summary" aria-label={c.title}>{[[c.total,report.total],[c.passing,report.passing],[c.queued,report.queued],[c.approved,report.approved]].map(([label,value])=><article className="admin-panel" key={label}><small>{label}</small><strong>{value}</strong></article>)}</section>
    <section className="admin-panel visual-review-queue"><header><div><p className="section-kicker">{c.queue}</p><h2>{report.needsReview} / {report.total}</h2><p>{c.queueLead}</p></div></header><div className="visual-review-grid">{report.items.map(item=><article key={item.id} data-grade={item.grade}><div className="visual-review-preview">{item.coverUrl?<Image src={item.coverUrl} alt="" fill sizes="(max-width: 700px) 100vw, 360px" unoptimized/>:<span aria-hidden>∅</span>}<b>{item.score}</b></div><div className="visual-review-copy"><div><span>{item.locale} · {item.grade}</span><small>{item.width&&item.height?`${item.width} × ${item.height}`:"—"} · {item.bodyImageCount} {c.body}</small></div><h3>{item.title}</h3><ul>{item.risks.length?item.risks.map(risk=><li key={risk}>{labels[risk]??risk}</li>):<li className="quality-clean">{c.clean}</li>}</ul>{item.visualTask&&<details className="visual-brief"><summary>{c.brief} · {item.visualTask.status}</summary><strong>{c.context}</strong><p>{item.visualTask.sectionContext}</p><strong>{c.brief}</strong><p>{item.visualTask.proposedPrompt}</p><strong>{c.negative}</strong><p>{item.visualTask.negativePrompt}</p><label>{c.note}<textarea id={`note-${item.visualTask.id}`} maxLength={1000}/></label><div className="visual-actions">{[["review",c.reviewAction],["approve",c.approve],["reject",c.reject],["retry",c.retry]].map(([action,label])=><button type="button" key={action} disabled={Boolean(busy)} onClick={()=>void send(`${item.visualTask!.id}/${action}`,(document.getElementById(`note-${item.visualTask!.id}`)as HTMLTextAreaElement)?.value)}>{label}</button>)}</div></details>}<nav><Link href={`/${item.locale}/articles/${item.slug}`} target="_blank">{c.open} ↗</Link><Link href={`/${locale}/admin/articles/${item.id}`}>{c.edit}</Link></nav></div></article>)}</div></section>
  </>;
}
