import Image from "next/image";
import Link from "next/link";
import type { Locale } from "@/i18n/config";

export type VisualQualityReport={checkedAt:string;total:number;passing:number;needsReview:number;missingCover:number;textRisk:number;averageScore:number;items:{id:string;locale:string;slug:string;title:string;publishedAt:string|null;score:number;grade:string;risks:string[];bodyImageCount:number;coverUrl:string|null;coverAltText:string|null;width:number|null;height:number|null;optimizedBytes:number|null}[]};
const copy={
  "tr-TR":{eyebrow:"GÖRSEL ÜRETİM SERVİSİ",title:"Görsel Kalite Masası",lead:"Yayımdaki her makaleyi konu eşleşmesi, yazısız tasarım, mobil kırpma, performans ve kullanım hakkı kapılarında tarar.",total:"Yayımdaki makale",passing:"Kapıdan geçen",review:"İnceleme kuyruğu",average:"Ortalama kalite",queue:"Öncelikli görsel kuyruğu",queueLead:"En düşük puanlı makaleler önce; sağlam görsel otomatik değiştirilmez.",open:"Makaleyi aç",edit:"Editörde incele",coverMissing:"Kapak eksik",altMissing:"Alt metin eksik",topicMismatch:"Konu eşleşmesi zayıf",textRisk:"Yazı / logo riski",cropRisk:"Mobil kırpma riski",notOptimized:"Optimize edilmemiş",oversized:"Dosya büyük",rightsMissing:"Kaynak / hak bilgisi eksik",bodyMissing:"Gövde görseli eksik",dimensionsUnknown:"Boyut bilinmiyor",clean:"Tüm otomatik kapılar temiz",body:"gövde görseli"},
  "en-US":{eyebrow:"VISUAL GENERATION SERVICE",title:"Visual Quality Desk",lead:"Audits every published story for topic fit, text-free design, mobile crop, performance and rights gates.",total:"Published stories",passing:"Passing",review:"Review queue",average:"Average quality",queue:"Priority visual queue",queueLead:"Lowest scores first; healthy visuals are never replaced automatically.",open:"Open story",edit:"Review in editor",coverMissing:"Missing cover",altMissing:"Missing alt text",topicMismatch:"Weak topic match",textRisk:"Text / logo risk",cropRisk:"Mobile crop risk",notOptimized:"Not optimized",oversized:"Oversized file",rightsMissing:"Missing rights metadata",bodyMissing:"Missing body visual",dimensionsUnknown:"Unknown dimensions",clean:"All automated gates clear",body:"body visuals"},
  "de-DE":{eyebrow:"BILDERZEUGUNGSDIENST",title:"Visueller Qualitätsdesk",lead:"Prüft jeden veröffentlichten Beitrag auf Themenbezug, textfreie Gestaltung, mobilen Beschnitt, Leistung und Bildrechte.",total:"Veröffentlichte Beiträge",passing:"Bestanden",review:"Prüfwarteschlange",average:"Durchschnitt",queue:"Priorisierte Bildwarteschlange",queueLead:"Niedrigste Werte zuerst; gute Bilder werden nie automatisch ersetzt.",open:"Beitrag öffnen",edit:"Im Editor prüfen",coverMissing:"Titelbild fehlt",altMissing:"Alt-Text fehlt",topicMismatch:"Schwacher Themenbezug",textRisk:"Text-/Logo-Risiko",cropRisk:"Risiko beim mobilen Beschnitt",notOptimized:"Nicht optimiert",oversized:"Datei zu groß",rightsMissing:"Bildrechte fehlen",bodyMissing:"Inhaltsbild fehlt",dimensionsUnknown:"Abmessungen unbekannt",clean:"Alle automatischen Prüfungen bestanden",body:"Inhaltsbilder"},
  "fr-FR":{eyebrow:"SERVICE DE GÉNÉRATION VISUELLE",title:"Bureau qualité visuelle",lead:"Contrôle chaque article publié : pertinence, design sans texte, recadrage mobile, performance et droits.",total:"Articles publiés",passing:"Conformes",review:"File de vérification",average:"Qualité moyenne",queue:"File visuelle prioritaire",queueLead:"Scores les plus faibles en premier ; une image saine n’est jamais remplacée automatiquement.",open:"Ouvrir l’article",edit:"Vérifier dans l’éditeur",coverMissing:"Couverture absente",altMissing:"Texte alternatif absent",topicMismatch:"Pertinence faible",textRisk:"Risque texte / logo",cropRisk:"Risque de recadrage mobile",notOptimized:"Non optimisée",oversized:"Fichier trop lourd",rightsMissing:"Droits non renseignés",bodyMissing:"Visuel de corps absent",dimensionsUnknown:"Dimensions inconnues",clean:"Tous les contrôles automatiques sont validés",body:"visuels de corps"}
} satisfies Record<Locale,Record<string,string>>;

export function VisualQualityDesk({locale,report}:{locale:Locale;report:VisualQualityReport}){const c=copy[locale];const labels:Record<string,string>={"missing-cover":c.coverMissing,"missing-alt":c.altMissing,"topic-mismatch":c.topicMismatch,"text-risk":c.textRisk,"unsafe-crop":c.cropRisk,"not-optimized":c.notOptimized,oversized:c.oversized,"missing-rights":c.rightsMissing,"missing-body-visual":c.bodyMissing,"unknown-dimensions":c.dimensionsUnknown};return <>
  <header className="visual-desk-hero"><div><p className="section-kicker">{c.eyebrow}</p><h1>{c.title}</h1><p>{c.lead}</p></div><div className="visual-score-dial" aria-label={`${c.average}: ${report.averageScore}`}><strong>{report.averageScore}</strong><span>/ 100</span></div></header>
  <section className="visual-quality-summary" aria-label={c.title}>{[[c.total,report.total],[c.passing,report.passing],[c.review,report.needsReview],[c.average,report.averageScore]].map(([label,value])=><article className="admin-panel" key={label}><small>{label}</small><strong>{value}</strong></article>)}</section>
  <section className="admin-panel visual-review-queue"><header><div><p className="section-kicker">{c.queue}</p><h2>{report.needsReview} / {report.total}</h2><p>{c.queueLead}</p></div></header><div className="visual-review-grid">{report.items.map(item=><article key={item.id} data-grade={item.grade}><div className="visual-review-preview">{item.coverUrl?<Image src={item.coverUrl} alt="" fill sizes="(max-width: 700px) 100vw, 360px" unoptimized/>:<span aria-hidden>∅</span>}<b>{item.score}</b></div><div className="visual-review-copy"><div><span>{item.locale} · {item.grade}</span><small>{item.width&&item.height?`${item.width} × ${item.height}`:"—"} · {item.bodyImageCount} {c.body}</small></div><h3>{item.title}</h3><ul>{item.risks.length?item.risks.map(risk=><li key={risk}>{labels[risk]??risk}</li>):<li className="quality-clean">{c.clean}</li>}</ul><nav><Link href={`/${item.locale}/articles/${item.slug}`} target="_blank">{c.open} ↗</Link><Link href={`/${locale}/admin/articles/${item.id}`}>{c.edit}</Link></nav></div></article>)}</div></section>
  </>}
