import type { Locale } from "@/i18n/config";
import type { WebVitalsDashboard } from "@/lib/admin-api";
const copy={
  "tr-TR":{title:"Yayın performansı",intro:"Ölçüm izni veren ziyaretçilerin 28 günlük gerçek kullanıcı p75 sonuçları; SEO sıralaması veya tüm ziyaretçiler için garanti değildir.",within:"Bütçe içinde",outside:"Bütçe dışında",insufficient:"Yeterli örnek yok",samples:"örnek",empty:"Henüz izinli saha ölçümü yok.",mobile:"Mobil",desktop:"Masaüstü"},
  "en-US":{title:"Publishing performance",intro:"28-day real-user p75 from visitors who consented to measurement; not a ranking or all-visitor guarantee.",within:"Within budget",outside:"Outside budget",insufficient:"Not enough samples",samples:"samples",empty:"No consented field measurements yet.",mobile:"Mobile",desktop:"Desktop"},
  "de-DE":{title:"Veröffentlichungsleistung",intro:"28-Tage-p75 echter Nutzer mit Messzustimmung; keine Ranking- oder Garantie für alle Besucher.",within:"Im Budget",outside:"Außerhalb des Budgets",insufficient:"Nicht genügend Messwerte",samples:"Messwerte",empty:"Noch keine zugestimmten Felddaten.",mobile:"Mobil",desktop:"Desktop"},
  "fr-FR":{title:"Performance des publications",intro:"p75 sur 28 jours des visiteurs ayant consenti à la mesure ; ni classement ni garantie pour tous.",within:"Dans le budget",outside:"Hors budget",insufficient:"Échantillon insuffisant",samples:"mesures",empty:"Aucune mesure terrain consentie.",mobile:"Mobile",desktop:"Ordinateur"}
} as const;
export function WebVitalsBudget({data,locale}:{data:WebVitalsDashboard;locale:Locale}){const c=copy[locale];return <section className="admin-panel" aria-labelledby="web-vitals-title"><p className="section-kicker">CORE WEB VITALS</p><h2 id="web-vitals-title">{c.title}</h2><p>{c.intro}</p><div className="authority-queue">{data.cohorts.map(item=>{const enough=item.samples>=data.minimumSamples,state=enough?(item.passes?c.within:c.outside):c.insufficient,unit=item.metric==="CLS"?"":" ms",viewport=item.viewport==="mobile"?c.mobile:c.desktop,statusClass=!enough?"neutral":item.passes?"review":"critical";return <article key={`${item.locale}-${item.route}-${item.viewport}-${item.metric}`}><strong className={`score score-${statusClass}`}>{item.p75}{unit}</strong><div><h3>{item.metric} · {item.locale} · {item.route} · {viewport}</h3><p>{state}; p75 {item.p75}{unit}, budget {item.budget}{unit}.</p><small>{item.samples} {c.samples}</small></div></article>})}{data.cohorts.length===0&&<p>{c.empty}</p>}</div></section>}
