"use client";
import { useEffect, useState } from "react";
import type { Locale } from "@/i18n/config";
import { pushCopy } from "@/i18n/push-copy";
import type { PushPreference } from "@/lib/admin-api";

function decodeKey(value:string){const padded=value+"=".repeat((4-value.length%4)%4);const raw=atob(padded.replace(/-/g,"+").replace(/_/g,"/"));return Uint8Array.from(raw,char=>char.charCodeAt(0));}
export function PushPreferences({locale,initial}:{locale:Locale;initial:PushPreference|null}){
  const copy=pushCopy[locale]; const [supported,setSupported]=useState<boolean|null>(null); const [permission,setPermission]=useState<NotificationPermission>("default"); const [enabled,setEnabled]=useState(initial?.enabled??false); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [start,setStart]=useState(initial?.preference?.quietStartsAt??22); const [end,setEnd]=useState(initial?.preference?.quietEndsAt??7);
  useEffect(()=>{const timer=window.setTimeout(()=>{const ok="serviceWorker" in navigator&&"PushManager" in window&&"Notification" in window;setSupported(ok);if(ok)setPermission(Notification.permission);},0);return()=>window.clearTimeout(timer);},[]);
  async function csrf(){const response=await fetch("/api/admin/auth/csrf",{cache:"no-store"});return ((await response.json())as{token:string}).token;}
  async function enable(){if(!initial?.available||!initial.publicKey)return;setBusy(true);setMessage("");try{const next=await Notification.requestPermission();setPermission(next);if(next!=="granted")return;const registration=await navigator.serviceWorker.register("/boecl-push-worker.js");const subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:decodeKey(initial.publicKey)});const json=subscription.toJSON();const response=await fetch("/api/admin/account/push",{method:"PUT",headers:{"content-type":"application/json","x-csrf-token":await csrf()},body:JSON.stringify({endpoint:json.endpoint,p256dh:json.keys?.p256dh,auth:json.keys?.auth,locale,quietStartsAt:start,quietEndsAt:end})});if(!response.ok)throw new Error();setEnabled(true);setMessage(copy.saved);}catch{setMessage(copy.failed);}finally{setBusy(false);}}
  async function disable(){setBusy(true);setMessage("");try{const registration=await navigator.serviceWorker.getRegistration("/boecl-push-worker.js");await (await registration?.pushManager.getSubscription())?.unsubscribe();const response=await fetch("/api/admin/account/push",{method:"DELETE",headers:{"x-csrf-token":await csrf()}});if(!response.ok)throw new Error();setEnabled(false);setMessage(copy.saved);}catch{setMessage(copy.failed);}finally{setBusy(false);}}
  const state=supported===false?copy.unsupported:!initial?.available?copy.unavailable:permission==="denied"?copy.denied:enabled?copy.enabled:"";
  return <section className="push-preferences" aria-labelledby="push-preferences-title"><p className="section-kicker">{copy.kicker}</p><h2 id="push-preferences-title">{copy.title}</h2><p>{copy.description}</p><p className="push-privacy">{copy.privacy}</p><fieldset disabled={busy||!supported||!initial?.available||permission==="denied"}><legend>{copy.quiet}</legend><label>{copy.start}<select value={start} onChange={e=>setStart(Number(e.target.value))}>{Array.from({length:24},(_,hour)=><option key={hour} value={hour}>{String(hour).padStart(2,"0")}:00</option>)}</select></label><label>{copy.end}<select value={end} onChange={e=>setEnd(Number(e.target.value))}>{Array.from({length:24},(_,hour)=><option key={hour} value={hour}>{String(hour).padStart(2,"0")}:00</option>)}</select></label><small>{copy.quietHelp}</small></fieldset>{enabled?<button type="button" disabled={busy} onClick={()=>void disable()}>{copy.disable}</button>:<button type="button" disabled={busy||!supported||!initial?.available||permission==="denied"} onClick={()=>void enable()}>{copy.enable}</button>}<p role={message===copy.failed?"alert":"status"}>{message||state}</p></section>;
}
