import Link from "next/link";
import { redirect } from "next/navigation";
import { hasLocale, type Locale } from "@/i18n/config";
import { getAdminSession, getTrafficDashboard, getWebVitalsDashboard } from "@/lib/admin-api";
import { WebVitalsBudget } from "@/components/admin/web-vitals-budget";

const copy = {
  "tr-TR": { kicker:"İÇERİK OTORİTESİ", title:"Kaynak kalitesi ve trafik fırsatları", intro:"Türkçe yayın arşivini kaynak çeşitliliği, SEO bütünlüğü ve gerçek okuma etkisiyle önceliklendirin.", published:"Yayındaki içerik", score:"Ortalama otorite", strong:"Güçlü içerik", critical:"Kritik açık", sourceGap:"Kaynağı olmayan", single:"Tek kaynaklı", evidence:"Kaynak kapsamı", evidenceIntro:"Puan yalnız mevcut kaynak, bağımsız alan adı, HTTPS, SEO, kapak ve taxonomy kanıtlarından hesaplanır; doğrulanmış kaynak iddiası değildir.", domains:"Kaynak ekosistemi", domainsIntro:"Arşivde en çok atıf alan alan adları", articles:"içerik", citations:"atıf", queue:"Öncelikli iyileştirme kuyruğu", queueIntro:"En düşük otorite puanı ve ardından mevcut trafik etkisine göre sıralı.", edit:"İyileştir →", sources:"kaynak", independent:"alan adı", views:"görüntülenme", empty:"Kaynak kalitesi açığı bulunamadı.", risks:{missing_sources:"Kaynak yok",single_source:"Tek kaynağa dayanıyor",single_domain:"Kaynaklar aynı alan adında",insecure_source:"HTTPS olmayan kaynak",missing_seo:"SEO alanları eksik",missing_cover:"Kapak eksik",missing_category:"Kategori eksik",missing_tags:"Etiket eksik"}},
  "en-US": { kicker:"CONTENT AUTHORITY", title:"Source quality and traffic opportunities", intro:"Prioritize the archive through source diversity, SEO integrity, and measured reading impact.", published:"Published stories", score:"Average authority", strong:"Strong stories", critical:"Critical gaps", sourceGap:"Without sources", single:"Single-source", evidence:"Evidence coverage", evidenceIntro:"Scores use only existing sources, independent domains, HTTPS, SEO, cover, and taxonomy evidence; they do not claim verification.", domains:"Source ecosystem", domainsIntro:"Most cited domains across the archive", articles:"stories", citations:"citations", queue:"Priority improvement queue", queueIntro:"Ordered by lowest authority score, then existing traffic impact.", edit:"Improve →", sources:"sources", independent:"domains", views:"views", empty:"No source-quality gaps found.", risks:{missing_sources:"No sources",single_source:"Relies on one source",single_domain:"Sources share one domain",insecure_source:"Non-HTTPS source",missing_seo:"SEO fields missing",missing_cover:"Cover missing",missing_category:"Category missing",missing_tags:"Tags missing"}},
  "de-DE": { kicker:"INHALTSAUTORITÄT", title:"Quellenqualität und Traffic-Chancen", intro:"Priorisieren Sie das Archiv nach Quellenvielfalt, SEO-Integrität und gemessener Lesewirkung.", published:"Veröffentlichte Beiträge", score:"Ø Autorität", strong:"Starke Beiträge", critical:"Kritische Lücken", sourceGap:"Ohne Quellen", single:"Nur eine Quelle", evidence:"Quellenabdeckung", evidenceIntro:"Der Wert nutzt nur vorhandene Quellen, unabhängige Domains, HTTPS, SEO, Titelbild und Taxonomie; er ist kein Verifizierungsnachweis.", domains:"Quellenökosystem", domainsIntro:"Meistzitierte Domains im Archiv", articles:"Beiträge", citations:"Zitate", queue:"Priorisierte Verbesserung", queueIntro:"Nach niedrigstem Autoritätswert und danach Traffic-Wirkung sortiert.", edit:"Verbessern →", sources:"Quellen", independent:"Domains", views:"Aufrufe", empty:"Keine Quellenlücken gefunden.", risks:{missing_sources:"Keine Quellen",single_source:"Nur eine Quelle",single_domain:"Gleiche Domain",insecure_source:"Quelle ohne HTTPS",missing_seo:"SEO fehlt",missing_cover:"Titelbild fehlt",missing_category:"Kategorie fehlt",missing_tags:"Tags fehlen"}},
  "fr-FR": { kicker:"AUTORITÉ ÉDITORIALE", title:"Qualité des sources et potentiel de trafic", intro:"Priorisez les archives selon la diversité des sources, l’intégrité SEO et l’impact de lecture mesuré.", published:"Articles publiés", score:"Autorité moyenne", strong:"Articles solides", critical:"Lacunes critiques", sourceGap:"Sans source", single:"Source unique", evidence:"Couverture des preuves", evidenceIntro:"Le score repose uniquement sur les sources, domaines indépendants, HTTPS, SEO, image et taxonomie existants ; il ne constitue pas une vérification.", domains:"Écosystème des sources", domainsIntro:"Domaines les plus cités dans les archives", articles:"articles", citations:"citations", queue:"File d’amélioration prioritaire", queueIntro:"Classée par score d’autorité, puis par impact de trafic existant.", edit:"Améliorer →", sources:"sources", independent:"domaines", views:"vues", empty:"Aucune lacune de source détectée.", risks:{missing_sources:"Aucune source",single_source:"Une seule source",single_domain:"Même domaine",insecure_source:"Source sans HTTPS",missing_seo:"SEO manquant",missing_cover:"Image manquante",missing_category:"Catégorie manquante",missing_tags:"Tags manquants"}},
} as const;

export default async function TrafficPage({ params }: PageProps<"/[locale]/admin/traffic">) {
  const { locale } = await params;
  if (!hasLocale(locale)) redirect("/tr-TR/admin/login");
  const session = await getAdminSession();
  if (!session) redirect(`/${locale}/admin/login`);
  if (!session.roles.some((role) => ["Owner", "Admin"].includes(role))) redirect(`/${locale}/admin`);
  const [data,vitals] = await Promise.all([getTrafficDashboard(locale),getWebVitalsDashboard()]);
  const c = copy[locale as Locale];
  if (!data) return <main className="admin-shell"><p>{c.empty}</p></main>;
  return <main className="admin-shell admin-dashboard-shell">
    <header className="admin-command-header authority-header"><div><p className="section-kicker">{c.kicker}</p><h1>{c.title}</h1><p>{c.intro}</p></div><strong className="authority-score">{data.authority.averageScore}<small>/100</small></strong></header>
    <section className="overview-kpis authority-kpis"><article><span>{c.published}</span><strong>{data.published}</strong><small>{locale}</small></article><article><span>{c.strong}</span><strong>{data.authority.strong}</strong><small>80–100</small></article><article><span>{c.critical}</span><strong>{data.authority.critical}</strong><small>0–49</small></article><article><span>{c.sourceGap}</span><strong>{data.authority.withoutSources}</strong><small>{c.single}: {data.authority.singleSource}</small></article></section>
    <div className="traffic-grid authority-grid"><section className="admin-panel"><p className="section-kicker">{c.evidence}</p><h2>{c.score}: {data.authority.averageScore}/100</h2><p>{c.evidenceIntro}</p><div className="authority-band"><span><b>{data.authority.strong}</b> 80–100</span><span><b>{data.authority.needsWork}</b> 50–79</span><span><b>{data.authority.critical}</b> 0–49</span></div></section><section className="admin-panel"><p className="section-kicker">{c.domains}</p><h2>{c.domainsIntro}</h2><div className="source-domain-list">{data.sourceDomains.map(item=><div key={item.domain}><strong>{item.domain}</strong><span>{item.articles} {c.articles} · {item.citations} {c.citations}</span></div>)}</div></section></div>
    <section className="admin-panel"><p className="section-kicker">{c.queue}</p><h2>{c.queueIntro}</h2><div className="authority-queue">{data.opportunities.map(item=><article key={item.id}><strong className={`score score-${item.authorityScore<50?"critical":"review"}`}>{item.authorityScore}</strong><div><h3>{item.title}</h3><p>{item.risks.map(risk=>c.risks[risk]).join(" · ")}</p><small>{item.sourceCount} {c.sources} · {item.domainCount} {c.independent} · {item.views} {c.views}</small></div><Link href={`/${locale}/admin/articles/${item.id}`}>{c.edit}</Link></article>)}{data.opportunities.length===0&&<p>{c.empty}</p>}</div></section>
    {vitals&&<WebVitalsBudget data={vitals} locale={locale as Locale}/>}
  </main>;
}
