import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { SiteHeader } from "@/components/site-header";
import { siteConfig } from "@/config/site";
import { getDictionary } from "@/i18n/get-dictionary";
import { hasLocale } from "@/i18n/config";
import { getPublishedArticle } from "@/lib/public-api";
import { absoluteUrl } from "@/lib/site-url";

export const dynamic = "force-dynamic";
export async function generateMetadata({ params }: PageProps<"/[locale]/articles/[slug]">): Promise<Metadata> {const {locale,slug}=await params;if(!hasLocale(locale))return{};const article=await getPublishedArticle(locale,slug);if(!article)return{};const languages=Object.fromEntries(article.translations.map(item=>[item.locale,`/${item.locale}/articles/${item.slug}`]));return{title:article.seoTitle??`${article.title} — ${siteConfig.name}`,description:article.seoDescription??article.summary,alternates:{canonical:`/${locale}/articles/${slug}`,languages},openGraph:{type:"article",title:article.seoTitle??article.title,description:article.seoDescription??article.summary,publishedTime:article.publishedAt,modifiedTime:article.updatedAt,url:`/${locale}/articles/${slug}`,siteName:siteConfig.name}}}

export default async function ArticlePage({params}:PageProps<"/[locale]/articles/[slug]">){const {locale,slug}=await params;if(!hasLocale(locale))notFound();const [article,dictionary]=await Promise.all([getPublishedArticle(locale,slug),getDictionary(locale)]);if(!article)notFound();const paragraphs=article.body.split(/\r?\n\s*\r?\n/).filter(Boolean);const structuredData={"@context":"https://schema.org","@type":"Article",headline:article.title,description:article.summary,datePublished:article.publishedAt,dateModified:article.updatedAt,inLanguage:locale,author:article.authors.map(author=>({"@type":"Person",name:author.displayName})),mainEntityOfPage:absoluteUrl(`/${locale}/articles/${slug}`),publisher:{"@type":"Organization",name:siteConfig.name}};return <div className="site-shell"><SiteHeader locale={locale}/><main className="article-page"><Link className="back-link" href={`/${locale}`}>← {dictionary.navigation.home}</Link><article><header><p className="section-kicker">{article.type}</p><h1>{article.title}</h1><p className="article-lead">{article.summary}</p>{article.authors.length>0&&<p className="article-byline">{article.authors.map(x=>x.displayName).join(", ")}</p>}<time dateTime={article.publishedAt}>{new Intl.DateTimeFormat(locale,{dateStyle:"long"}).format(new Date(article.publishedAt))}</time>{article.categories.length>0&&<div className="article-taxonomy">{article.categories.map(x=><span key={x.slug}>{x.name}</span>)}</div>}</header><div className="article-body">{paragraphs.map((paragraph,index)=><p key={index}>{paragraph}</p>)}</div>{article.tags.length>0&&<footer className="article-taxonomy">{article.tags.map(x=><span key={x.slug}>#{x.name}</span>)}</footer>}{article.sources.length>0&&<aside className="article-sources"><h2>Sources</h2><ul>{article.sources.map(x=><li key={x.url}><a href={x.url} rel="nofollow noopener noreferrer" target="_blank">{x.name}</a></li>)}</ul></aside>}</article><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData).replace(/</g,"\\u003c")}}/></main></div>}
