import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { SiteHeader } from "@/components/site-header";
import { hasLocale, locales } from "@/i18n/config";
import { sourceCopy } from "@/i18n/source-copy";
import { getPublicSourceIndex } from "@/lib/public-api";
export const dynamic="force-dynamic";
export async function generateMetadata({params}:PageProps<"/[locale]/sources">):Promise<Metadata>{const {locale}=await params;if(!hasLocale(locale))return{};const copy=sourceCopy[locale];return{title:copy.title,description:copy.description,alternates:{canonical:`/${locale}/sources`,languages:Object.fromEntries(locales.map(code=>[code,`/${code}/sources`]))}}}
export default async function SourcesPage({params}:PageProps<"/[locale]/sources">){
 const {locale}=await params;if(!hasLocale(locale))notFound();const index=await getPublicSourceIndex(locale),copy=sourceCopy[locale];
 const percent=(value:number,total:number)=>total===0?0:Math.round(value/total*100);
 return <div className="site-shell"><SiteHeader locale={locale}/><main id="main-content" className="source-center"><header className="source-center-hero"><div><p className="section-kicker">{copy.eyebrow}</p><h1>{copy.title}</h1><p>{copy.description}</p></div><dl><div><dt>{copy.sources}</dt><dd>{index.totalSources}</dd></div><div><dt>{copy.citations}</dt><dd>{index.totalCitations}</dd></div></dl></header><section className="source-coverage" aria-labelledby="source-coverage-title"><header><div><p className="section-kicker">BOECL</p><h2 id="source-coverage-title">{copy.coverageTitle}</h2></div><p>{copy.coverageDescription}</p></header><dl><div><dt>{copy.sourcedCoverage}</dt><dd>{percent(index.sourcedArticleCount,index.totalArticles)}<small>%</small></dd><span>{index.sourcedArticleCount} / {index.totalArticles}</span></div><div><dt>{copy.multiSourceCoverage}</dt><dd>{percent(index.multiDomainArticleCount,index.sourcedArticleCount)}<small>%</small></dd><span>{index.multiDomainArticleCount} / {index.sourcedArticleCount}</span></div><div><dt>{copy.reviewCoverage}</dt><dd>{percent(index.reviewedSourceCount,index.totalSources)}<small>%</small></dd><span>{index.reviewedSourceCount} / {index.totalSources}</span></div></dl></section>{index.sources.length===0?<p className="muted">{copy.empty}</p>:<section className="source-domain-grid" aria-label={copy.sources}>{index.sources.map((source,rank)=><article key={source.domain}><span className="source-rank">{String(rank+1).padStart(2,"0")}</span><p className="section-kicker">{source.kind==="Unclassified"?copy.unclassified:copy.kinds[source.kind]}</p><h2><Link href={`/${locale}/sources/${source.domain}`}>{source.domain}</Link></h2><p>{source.sourceName}</p><div className="source-statline"><strong>{source.articleCount}</strong> {copy.articles}<span>·</span><strong>{source.citationCount}</strong> {copy.citations}</div><p className={`source-review source-review-${source.reviewState.toLowerCase()}`}>{source.reviewState==="Current"?copy.currentReview:source.reviewState==="ReviewDue"?copy.reviewDue:copy.unclassified}{source.lastReviewedAt&&<> · <time dateTime={source.lastReviewedAt}>{new Intl.DateTimeFormat(locale,{dateStyle:"medium"}).format(new Date(source.lastReviewedAt))}</time></>}</p><Link className="source-open" href={`/${locale}/sources/${source.domain}`}>{copy.open} →</Link></article>)}</section>}</main></div>;
}
