import type {Locale} from "./config";
type Document={title:string;updated:string;sections:{heading:string;body:string}[]};
const updated="8 August 2026";
export const legalDocuments:Record<Locale,Record<string,Document>>={
 "tr-TR":{
  privacy:{title:"Gizlilik politikası",updated,sections:[{heading:"Toplanan bilgiler",body:"BOECL, hizmet güvenliği için IP adresi, istek zamanı, tarayıcı bilgisi ve hata kayıtlarını sınırlı süreyle işler. Hesap sahiplerinin e-posta adresi ve görünen adı hesap yönetimi için saklanır."},{heading:"Amaç ve saklama",body:"Kayıtlar güvenlik, hata çözümü ve hizmetin ölçülmesi için kullanılır; satılmaz. Zorunlu kayıtlar operasyonel ihtiyaç sona erdiğinde silinir veya anonimleştirilir."},{heading:"Haklarınız",body:"Erişim, düzeltme veya silme talebi için programlamaw@gmail.com adresine yazabilirsiniz."}]},
  cookies:{title:"Çerez politikası",updated,sections:[{heading:"Zorunlu çerezler",body:"Oturum güvenliği, CSRF koruması ve dil tercihi için gerekli çerezler kullanılabilir."},{heading:"İsteğe bağlı ölçüm",body:"İsteğe bağlı analiz yalnızca açık tercihinizden sonra etkinleşir. Tercihinizi tarayıcınızdan değiştirebilirsiniz."}]},
  terms:{title:"Kullanım şartları",updated,sections:[{heading:"İçerik",body:"BOECL içerikleri genel bilgilendirme amaçlıdır; profesyonel hukuk, sağlık veya yatırım tavsiyesi değildir."},{heading:"Kullanım",body:"Kaynak göstererek kısa alıntı yapılabilir. İçeriğin tamamının izinsiz çoğaltılması ve hizmete zarar veren otomatik kullanım yasaktır."}]},
  editorial:{title:"Yayın ve düzeltme ilkeleri",updated,sections:[{heading:"Editoryal standart",body:"Yayınlar kaynak, bağlam ve insan editör kontrolüyle hazırlanır. AI destekli taslaklar insan onayı olmadan yayımlanmaz."},{heading:"Düzeltmeler",body:"Maddi hata bildirimleri incelenir; gerekli düzeltmeler şeffaf biçimde uygulanır. Bildirimler programlamaw@gmail.com adresine gönderilebilir."},{heading:"Kaynaklar",body:"Mümkün olduğunda birincil kaynaklara bağlantı verilir; sponsorlu veya ticari ilişkiler açıkça işaretlenir."}]},
  contact:{title:"İletişim",updated,sections:[{heading:"BOECL ile iletişim",body:"Editoryal düzeltme, gizlilik, iş birliği ve genel sorular için programlamaw@gmail.com adresini kullanabilirsiniz."}]}
 },
 "en-US":{
  privacy:{title:"Privacy policy",updated,sections:[{heading:"Information collected",body:"BOECL processes IP address, request time, browser details and error logs for service security. Account email and display name are stored for account administration."},{heading:"Purpose and retention",body:"Records support security, troubleshooting and service measurement; they are not sold. Operational records are deleted or anonymized when no longer needed."},{heading:"Your rights",body:"Contact programlamaw@gmail.com to request access, correction or deletion."}]},
  cookies:{title:"Cookie policy",updated,sections:[{heading:"Essential cookies",body:"Cookies may be required for secure sessions, CSRF protection and language preferences."},{heading:"Optional measurement",body:"Optional analytics activates only after your explicit choice. You can revise the choice in your browser."}]},
  terms:{title:"Terms of use",updated,sections:[{heading:"Content",body:"BOECL content is general information and not professional legal, medical or investment advice."},{heading:"Use",body:"Short attributed quotations are allowed. Republishing complete works without permission or automated use that harms the service is prohibited."}]},
  editorial:{title:"Editorial and corrections policy",updated,sections:[{heading:"Editorial standard",body:"Publications use sources, context and human editorial review. AI-assisted drafts are never published without human approval."},{heading:"Corrections",body:"Material error reports are reviewed and corrections are made transparently. Send reports to programlamaw@gmail.com."},{heading:"Sources",body:"Primary sources are linked where possible; sponsorships and commercial relationships are disclosed."}]},
  contact:{title:"Contact",updated,sections:[{heading:"Contact BOECL",body:"For corrections, privacy, partnerships and general questions, email programlamaw@gmail.com."}]}
 },
 "de-DE":{
  privacy:{title:"Datenschutzerklärung",updated,sections:[{heading:"Erhobene Informationen",body:"BOECL verarbeitet IP-Adresse, Anfragezeit, Browserdaten und Fehlerprotokolle zur Sicherheit. E-Mail und Anzeigename von Konten dienen der Kontoverwaltung."},{heading:"Zweck und Aufbewahrung",body:"Daten dienen Sicherheit, Fehlerbehebung und Messung; sie werden nicht verkauft und nach Wegfall des Zwecks gelöscht oder anonymisiert."},{heading:"Ihre Rechte",body:"Anfragen zu Auskunft, Berichtigung oder Löschung an programlamaw@gmail.com senden."}]},
  cookies:{title:"Cookie-Richtlinie",updated,sections:[{heading:"Notwendige Cookies",body:"Cookies können für sichere Sitzungen, CSRF-Schutz und Spracheinstellungen erforderlich sein."},{heading:"Optionale Messung",body:"Optionale Analyse wird erst nach Ihrer ausdrücklichen Wahl aktiviert. Die Wahl kann im Browser geändert werden."}]},
  terms:{title:"Nutzungsbedingungen",updated,sections:[{heading:"Inhalte",body:"BOECL-Inhalte dienen der allgemeinen Information und sind keine professionelle Rechts-, Gesundheits- oder Anlageberatung."},{heading:"Nutzung",body:"Kurze Zitate mit Quellenangabe sind erlaubt. Vollständige unerlaubte Vervielfältigung und schädliche automatisierte Nutzung sind untersagt."}]},
  editorial:{title:"Redaktions- und Korrekturrichtlinie",updated,sections:[{heading:"Standard",body:"Veröffentlichungen beruhen auf Quellen, Kontext und menschlicher Prüfung. KI-Entwürfe werden nie ohne menschliche Freigabe veröffentlicht."},{heading:"Korrekturen",body:"Hinweise auf wesentliche Fehler werden geprüft und transparent korrigiert. Kontakt: programlamaw@gmail.com."},{heading:"Quellen",body:"Primärquellen werden möglichst verlinkt; Sponsoring und kommerzielle Beziehungen werden offengelegt."}]},
  contact:{title:"Kontakt",updated,sections:[{heading:"BOECL kontaktieren",body:"Für Korrekturen, Datenschutz, Kooperationen und allgemeine Fragen: programlamaw@gmail.com."}]}
 },
 "fr-FR":{
  privacy:{title:"Politique de confidentialité",updated,sections:[{heading:"Informations collectées",body:"BOECL traite l’adresse IP, l’heure de la requête, les informations du navigateur et les journaux d’erreurs pendant une durée limitée afin de sécuriser le service. L’adresse e-mail et le nom affiché des titulaires de compte sont conservés pour la gestion des comptes."},{heading:"Finalité et conservation",body:"Les journaux servent à la sécurité, à la résolution des erreurs et à la mesure du service ; ils ne sont pas vendus. Les données nécessaires sont supprimées ou anonymisées lorsque le besoin opérationnel prend fin."},{heading:"Vos droits",body:"Pour demander l’accès, la rectification ou la suppression de vos données, écrivez à programlamaw@gmail.com."}]},
  cookies:{title:"Politique relative aux cookies",updated,sections:[{heading:"Cookies essentiels",body:"Des cookies nécessaires peuvent être utilisés pour la sécurité des sessions, la protection CSRF et la préférence linguistique."},{heading:"Mesure facultative",body:"Les outils d’analyse facultatifs ne sont activés qu’après votre choix explicite. Vous pouvez modifier ce choix dans votre navigateur."}]},
  terms:{title:"Conditions d’utilisation",updated,sections:[{heading:"Contenu",body:"Les contenus de BOECL sont fournis à titre d’information générale ; ils ne constituent pas des conseils juridiques, médicaux ou financiers professionnels."},{heading:"Utilisation",body:"De courtes citations avec mention de la source sont autorisées. La reproduction intégrale sans autorisation et l’utilisation automatisée nuisible au service sont interdites."}]},
  editorial:{title:"Principes éditoriaux et politique de correction",updated,sections:[{heading:"Norme éditoriale",body:"Les publications sont préparées avec des sources, du contexte et une validation éditoriale humaine. Les brouillons assistés par IA ne sont jamais publiés sans approbation humaine."},{heading:"Corrections",body:"Les signalements d’erreurs importantes sont examinés et les corrections nécessaires sont appliquées de manière transparente. Les signalements peuvent être envoyés à programlamaw@gmail.com."},{heading:"Sources",body:"Des liens vers les sources primaires sont fournis lorsque cela est possible ; les parrainages et relations commerciales sont clairement signalés."}]},
  contact:{title:"Contact",updated,sections:[{heading:"Contacter BOECL",body:"Pour les corrections éditoriales, la confidentialité, les partenariats et les questions générales, écrivez à programlamaw@gmail.com."}]}
 }};
export const legalLabels={"tr-TR":{privacy:"Gizlilik",cookies:"Çerezler",terms:"Kullanım şartları",editorial:"Yayın ilkeleri",contact:"İletişim",updated:"Güncelleme"},"en-US":{privacy:"Privacy",cookies:"Cookies",terms:"Terms",editorial:"Editorial policy",contact:"Contact",updated:"Updated"},"de-DE":{privacy:"Datenschutz",cookies:"Cookies",terms:"Bedingungen",editorial:"Redaktionsrichtlinie",contact:"Kontakt",updated:"Aktualisiert"},"fr-FR":{privacy:"Confidentialité",cookies:"Cookies",terms:"Conditions",editorial:"Principes éditoriaux",contact:"Contact",updated:"Mise à jour"}} satisfies Record<Locale,Record<string,string>>;
export const legalSlugs=["privacy","cookies","terms","editorial","contact"] as const;
