import type { Locale } from "./config";

type Copy={title:string;description:string;eyebrow:string;sources:string;citations:string;articles:string;latest:string;open:string;archiveTitle:(domain:string)=>string;archiveDescription:(domain:string)=>string;usedFor:string;sourceNames:string;back:string;empty:string};
export const sourceCopy:Record<Locale,Copy>={
  "tr-TR":{title:"Kaynak ve Güven Merkezi",description:"BOECL yayınlarında kullanılan açık web kaynaklarını, atıf yoğunluğunu ve bu kaynaklarla hazırlanan Türkçe içerikleri keşfedin.",eyebrow:"Editoryal şeffaflık",sources:"kaynak alanı",citations:"atıf",articles:"yayın",latest:"Son kaynak kullanımı",open:"Kaynak arşivini aç",archiveTitle:d=>`${d} kaynak arşivi`,archiveDescription:d=>`BOECL'in ${d} alan adına atıf verdiği yayımlanmış içerikler ve kaynak kullanım özeti.`,usedFor:"Bu kaynakla hazırlanan yayınlar",sourceNames:"Kayıtlı kaynak adları",back:"Tüm kaynaklar",empty:"Henüz yayımlanmış kaynak kaydı yok."},
  "en-US":{title:"Sources & Trust Center",description:"Explore the open-web sources cited by BOECL, citation depth, and the stories informed by them.",eyebrow:"Editorial transparency",sources:"source domains",citations:"citations",articles:"stories",latest:"Latest citation",open:"Open source archive",archiveTitle:d=>`${d} source archive`,archiveDescription:d=>`Published BOECL stories citing ${d}, with a transparent summary of source use.`,usedFor:"Stories informed by this source",sourceNames:"Recorded source names",back:"All sources",empty:"No published source records yet."},
  "de-DE":{title:"Quellen- und Vertrauenszentrum",description:"Entdecken Sie die von BOECL zitierten offenen Webquellen, die Zitiertiefe und die damit erstellten Beiträge.",eyebrow:"Redaktionelle Transparenz",sources:"Quelldomains",citations:"Zitate",articles:"Beiträge",latest:"Letzte Quellenverwendung",open:"Quellenarchiv öffnen",archiveTitle:d=>`Quellenarchiv ${d}`,archiveDescription:d=>`Veröffentlichte BOECL-Beiträge mit Verweisen auf ${d} und transparenter Übersicht der Quellennutzung.`,usedFor:"Beiträge auf Grundlage dieser Quelle",sourceNames:"Erfasste Quellennamen",back:"Alle Quellen",empty:"Noch keine veröffentlichten Quellenangaben."},
  "fr-FR":{title:"Centre des sources et de la confiance",description:"Explorez les sources web ouvertes citées par BOECL, la profondeur des citations et les publications qui s’en inspirent.",eyebrow:"Transparence éditoriale",sources:"domaines sources",citations:"citations",articles:"publications",latest:"Dernière citation",open:"Ouvrir l’archive de la source",archiveTitle:d=>`Archives de la source ${d}`,archiveDescription:d=>`Publications BOECL citant ${d}, avec un aperçu transparent de l’utilisation de cette source.`,usedFor:"Publications fondées sur cette source",sourceNames:"Noms de source enregistrés",back:"Toutes les sources",empty:"Aucune source publiée pour le moment."}
};
