// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Peletnapechkai.Api.Infrastructure.Persistence;

#nullable disable

namespace Peletnapechkai.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PublishingDbContext))]
    [Migration("20260811192933_AddHomepageCurationEngagementAndMembers")]
    partial class AddHomepageCurationEngagementAndMembers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Auditing.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("details_json");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId", "OccurredAt")
                        .HasDatabaseName("ix_audit_logs_entity_time");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Automation.AutomationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AutoSeo")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_seo");

                    b.Property<bool>("AutoTranslate")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_translate");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("CompletedItems")
                        .HasColumnType("integer")
                        .HasColumnName("completed_items");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("CurrentPhase")
                        .HasColumnType("integer")
                        .HasColumnName("current_phase");

                    b.Property<int>("FailedItems")
                        .HasColumnType("integer")
                        .HasColumnName("failed_items");

                    b.Property<bool>("IncludeImages")
                        .HasColumnType("boolean")
                        .HasColumnName("include_images");

                    b.Property<string>("LastMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_message");

                    b.Property<string>("ReportText")
                        .HasColumnType("text")
                        .HasColumnName("report_text");

                    b.Property<string>("RequestedArticleType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("requested_article_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.PrimitiveCollection<string[]>("TargetLocales")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("target_locales");

                    b.Property<int>("TotalItems")
                        .HasColumnType("integer")
                        .HasColumnName("total_items");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_automation_jobs_status_created");

                    b.ToTable("automation_jobs", (string)null);
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Content.ArticleEngagement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArticleLocalizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_localization_id");

                    b.Property<long>("EngagedSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("engaged_seconds");

                    b.Property<DateTimeOffset>("LastViewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_viewed_at");

                    b.Property<long>("ViewCount")
                        .HasColumnType("bigint")
                        .HasColumnName("view_count");

                    b.HasKey("Id");

                    b.HasIndex("ArticleLocalizationId")
                        .IsUnique()
                        .HasDatabaseName("ux_article_engagements_article");

                    b.ToTable("article_engagements", (string)null);
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Content.ArticleGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("article_groups", (string)null);
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Content.ArticleLocalization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArticleGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_group_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("CoverAltText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cover_alt_text");

                    b.Property<string>("CoverCaption")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("cover_caption");

                    b.Property<string>("CoverCredit")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("cover_credit");

                    b.Property<Guid?>("CoverMediaAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("cover_media_asset_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("GeneratedByAutomationJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("generated_by_automation_job_id");

                    b.Property<bool>("HasAffiliateLinks")
                        .HasColumnType("boolean")
                        .HasColumnName("has_affiliate_links");

                    b.Property<bool>("IsSponsored")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sponsored");

                    b.Property<Guid>("LocaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("locale_id");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<DateTimeOffset?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("SeoDescription")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("seo_description");

                    b.Property<string>("SeoTitle")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("seo_title");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("slug");

                    b.Property<string>("SponsorName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("sponsor_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CoverMediaAssetId");

                    b.HasIndex("GeneratedByAutomationJobId")
                        .HasDatabaseName("ix_article_localizations_generation_job");

                    b.HasIndex("ArticleGroupId", "LocaleId")
                        .IsUnique()
                        .HasDatabaseName("ux_article_localizations_group_locale");

                    b.HasIndex("LocaleId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_article_localizations_locale_slug");

                    b.HasIndex("LocaleId", "Status", "PublishedAt")
                        .HasDatabaseName("ix_article_localizations_publication");

                    b.ToTable("article_localizations", null, t =>
                        {
                            t.HasCheckConstraint("ck_article_localizations_slug_not_empty", "length(trim(slug)) > 0");

                            t.HasCheckConstraint("ck_article_localizations_title_not_empty", "length(trim(title)) > 0");
                        });
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Content.ArticleQualityChecklist", b =>
                {
                    b.Property<Guid>("ArticleLocalizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_localization_id");

                    b.Property<bool>("AuthorAndTaxonomy")
                        .HasColumnType("boolean")
                        .HasColumnName("author_and_taxonomy");

                    b.Property<bool>("CommercialDisclosure")
                        .HasColumnType("boolean")
                        .HasColumnName("commercial_disclosure");

                    b.Property<bool>("CoverAccessibility")
                        .HasColumnType("boolean")
                        .HasColumnName("cover_accessibility");

                    b.Property<bool>("LegalEditorialReview")
                        .HasColumnType("boolean")
                        .HasColumnName("legal_editorial_review");

                    b.Property<bool>("SeoMetadata")
                        .HasColumnType("boolean")
                        .HasColumnName("seo_metadata");

                    b.Property<bool>("SourcesVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("sources_verified");

                    b.Property<bool>("TitleAndSummary")
                        .HasColumnType("boolean")
                        .HasColumnName("title_and_summary");

                    b.Property<bool>("TranslationReviewed")
                        .HasColumnType("boolean")
                        .HasColumnName("translation_reviewed");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("ArticleLocalizationId");

                    b.ToTable("article_quality_checklists", (string)null);
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Content.ArticleRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArticleLocalizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_localization_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ArticleLocalizationId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ux_article_revisions_article_number");

                    b.ToTable("article_revisions", null, t =>
                        {
                            t.HasCheckConstraint("ck_article_revisions_number_positive", "number > 0");
                        });
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Content.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("bio");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("display_name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_authors_slug");

                    b.ToTable("authors", (string)null);
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Content.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("LocaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("locale_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("LocaleId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_categories_locale_slug");

                    b.ToTable("categories", null, t =>
                        {
                            t.HasCheckConstraint("ck_categories_name_not_empty", "length(trim(name)) > 0");

                            t.HasCheckConstraint("ck_categories_slug_not_empty", "length(trim(slug)) > 0");
                        });
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Content.EditorialComment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArticleLocalizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_localization_id");

                    b.Property<Guid?>("ArticleRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_revision_id");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_resolved");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_comment_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ArticleLocalizationId", "CreatedAt")
                        .HasDatabaseName("ix_editorial_comments_article_created");

                    b.ToTable("editorial_comments", (string)null);
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Content.EditorialTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArticleLocalizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_localization_id");

                    b.Property<Guid>("AssigneeUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("priority");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ArticleLocalizationId");

                    b.HasIndex("AssigneeUserId", "Status", "DueAt")
                        .HasDatabaseName("ix_editorial_tasks_assignee_status_due");

                    b.ToTable("editorial_tasks", (string)null);
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Content.HomepagePlacement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArticleLocalizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_localization_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LocaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("locale_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("section");

                    b.HasKey("Id");

                    b.HasIndex("ArticleLocalizationId");

                    b.HasIndex("LocaleId", "ArticleLocalizationId")
                        .IsUnique()
                        .HasDatabaseName("ux_homepage_placements_article");

                    b.HasIndex("LocaleId", "Section", "Position")
                        .IsUnique()
                        .HasDatabaseName("ux_homepage_placements_slot");

                    b.ToTable("homepage_placements", (string)null);
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Content.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ByteLength")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_length");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("character varying(127)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<long?>("OptimizedByteLength")
                        .HasColumnType("bigint")
                        .HasColumnName("optimized_byte_length");

                    b.Property<string>("OptimizedStorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("optimized_storage_key");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("ux_media_assets_storage_key");

                    b.ToTable("media_assets", null, t =>
                        {
                            t.HasCheckConstraint("ck_media_assets_byte_length_positive", "byte_length > 0");
                        });
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Content.SeoMetadata", b =>
                {
                    b.Property<Guid>("ArticleLocalizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_localization_id");

                    b.Property<string>("CanonicalUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("canonical_url");

                    b.Property<string>("OpenGraphDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("open_graph_description");

                    b.Property<string>("OpenGraphTitle")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("open_graph_title");

                    b.Property<string>("RobotsDirective")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("robots_directive");

                    b.Property<string>("StructuredDataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("structured_data_json");

                    b.HasKey("ArticleLocalizationId");

                    b.ToTable("seo_metadata", (string)null);
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Content.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique()
                        .HasDatabaseName("ux_sources_url");

                    b.ToTable("sources", (string)null);
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Content.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LocaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("locale_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("LocaleId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_tags_locale_slug");

                    b.ToTable("tags", null, t =>
                        {
                            t.HasCheckConstraint("ck_tags_name_not_empty", "length(trim(name)) > 0");

                            t.HasCheckConstraint("ck_tags_slug_not_empty", "length(trim(slug)) > 0");
                        });
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_roles_normalized_name");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0198f100-0000-7000-a000-000000000001"),
                            ConcurrencyStamp = "role-owner-v1",
                            Name = "Owner",
                            NormalizedName = "OWNER"
                        },
                        new
                        {
                            Id = new Guid("0198f100-0000-7000-a000-000000000002"),
                            ConcurrencyStamp = "role-admin-v1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("0198f100-0000-7000-a000-000000000003"),
                            ConcurrencyStamp = "role-editor-v1",
                            Name = "Editor",
                            NormalizedName = "EDITOR"
                        },
                        new
                        {
                            Id = new Guid("0198f100-0000-7000-a000-000000000004"),
                            ConcurrencyStamp = "role-author-v1",
                            Name = "Author",
                            NormalizedName = "AUTHOR"
                        },
                        new
                        {
                            Id = new Guid("0198f100-0000-7000-a000-000000000005"),
                            ConcurrencyStamp = "role-translator-v1",
                            Name = "Translator",
                            NormalizedName = "TRANSLATOR"
                        },
                        new
                        {
                            Id = new Guid("0198f100-0000-7000-a000-000000000006"),
                            ConcurrencyStamp = "role-seo-v1",
                            Name = "SEO",
                            NormalizedName = "SEO"
                        },
                        new
                        {
                            Id = new Guid("0198f100-0000-7000-a000-000000000007"),
                            ConcurrencyStamp = "role-member-v1",
                            Name = "Member",
                            NormalizedName = "MEMBER"
                        });
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_email");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_user_name");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Knowledge.KnowledgeArticleLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArticleLocalizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_localization_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("KnowledgeCandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("knowledge_candidate_id");

                    b.Property<DateTimeOffset>("LastVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_verified_at");

                    b.Property<Guid>("LastVerifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_verified_by_user_id");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("purpose");

                    b.Property<DateTimeOffset>("ReviewDueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("review_due_at");

                    b.HasKey("Id");

                    b.HasIndex("ArticleLocalizationId");

                    b.HasIndex("ReviewDueAt")
                        .HasDatabaseName("ix_knowledge_article_review_due");

                    b.HasIndex("KnowledgeCandidateId", "ArticleLocalizationId")
                        .IsUnique()
                        .HasDatabaseName("ux_knowledge_article_link");

                    b.ToTable("knowledge_article_links", (string)null);
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Knowledge.KnowledgeCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AiAssisted")
                        .HasColumnType("boolean")
                        .HasColumnName("ai_assisted");

                    b.Property<string>("Claim")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("claim");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("LocaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("locale_id");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("source_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("LocaleId", "Status", "UpdatedAt")
                        .HasDatabaseName("ix_knowledge_locale_status_updated");

                    b.ToTable("knowledge_candidates", (string)null);
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Localization.Locale", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("language_code");

                    b.Property<string>("NativeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("native_name");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid")
                        .HasColumnName("region_id");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_locales_code");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasDatabaseName("ux_locales_single_default")
                        .HasFilter("is_default");

                    b.HasIndex("RegionId");

                    b.ToTable("locales", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0198f100-0000-7000-9000-000000000001"),
                            Code = "tr-TR",
                            DisplayName = "Turkish (Türkiye)",
                            IsDefault = true,
                            IsEnabled = true,
                            LanguageCode = "tr",
                            NativeName = "Türkçe (Türkiye)",
                            RegionId = new Guid("0198f100-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0198f100-0000-7000-9000-000000000002"),
                            Code = "en-US",
                            DisplayName = "English (United States)",
                            IsDefault = false,
                            IsEnabled = true,
                            LanguageCode = "en",
                            NativeName = "English (United States)",
                            RegionId = new Guid("0198f100-0000-7000-8000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("0198f100-0000-7000-9000-000000000003"),
                            Code = "de-DE",
                            DisplayName = "German (Germany)",
                            IsDefault = false,
                            IsEnabled = true,
                            LanguageCode = "de",
                            NativeName = "Deutsch (Deutschland)",
                            RegionId = new Guid("0198f100-0000-7000-8000-000000000003")
                        });
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Localization.LocaleCountry", b =>
                {
                    b.Property<Guid>("LocaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("locale_id");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid")
                        .HasColumnName("country_id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.HasKey("LocaleId", "CountryId");

                    b.HasIndex("CountryId", "IsEnabled")
                        .HasDatabaseName("ix_locale_countries_country_enabled");

                    b.ToTable("locale_countries", (string)null);
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Localization.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("code");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_regions_code");

                    b.ToTable("regions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0198f100-0000-7000-8000-000000000001"),
                            Code = "TR",
                            CurrencyCode = "TRY",
                            IsEnabled = true,
                            Name = "Türkiye"
                        },
                        new
                        {
                            Id = new Guid("0198f100-0000-7000-8000-000000000002"),
                            Code = "US",
                            CurrencyCode = "USD",
                            IsEnabled = true,
                            Name = "United States"
                        },
                        new
                        {
                            Id = new Guid("0198f100-0000-7000-8000-000000000003"),
                            Code = "DE",
                            CurrencyCode = "EUR",
                            IsEnabled = true,
                            Name = "Germany"
                        });
                });

            modelBuilder.Entity("article_authors", b =>
                {
                    b.Property<Guid>("article_group_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("author_id")
                        .HasColumnType("uuid");

                    b.HasKey("article_group_id", "author_id");

                    b.HasIndex("author_id");

                    b.ToTable("article_authors", (string)null);
                });

            modelBuilder.Entity("article_categories", b =>
                {
                    b.Property<Guid>("article_localization_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("category_id")
                        .HasColumnType("uuid");

                    b.HasKey("article_localization_id", "category_id");

                    b.HasIndex("category_id");

                    b.ToTable("article_categories", (string)null);
                });

            modelBuilder.Entity("article_media_assets", b =>
                {
                    b.Property<Guid>("article_group_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("media_asset_id")
                        .HasColumnType("uuid");

                    b.HasKey("article_group_id", "media_asset_id");

                    b.HasIndex("media_asset_id");

                    b.ToTable("article_media_assets", (string)null);
                });

            modelBuilder.Entity("article_sources", b =>
                {
                    b.Property<Guid>("article_group_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("source_id")
                        .HasColumnType("uuid");

                    b.HasKey("article_group_id", "source_id");

                    b.HasIndex("source_id");

                    b.ToTable("article_sources", (string)null);
                });

            modelBuilder.Entity("article_tags", b =>
                {
                    b.Property<Guid>("article_localization_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("tag_id")
                        .HasColumnType("uuid");

                    b.HasKey("article_localization_id", "tag_id");

                    b.HasIndex("tag_id");

                    b.ToTable("article_tags", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Peletnapechkai.Api.Domain.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Peletnapechkai.Api.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Peletnapechkai.Api.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Peletnapechkai.Api.Domain.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Peletnapechkai.Api.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Peletnapechkai.Api.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Content.ArticleEngagement", b =>
                {
                    b.HasOne("Peletnapechkai.Api.Domain.Content.ArticleLocalization", "ArticleLocalization")
                        .WithOne()
                        .HasForeignKey("Peletnapechkai.Api.Domain.Content.ArticleEngagement", "ArticleLocalizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArticleLocalization");
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Content.ArticleLocalization", b =>
                {
                    b.HasOne("Peletnapechkai.Api.Domain.Content.ArticleGroup", "ArticleGroup")
                        .WithMany("Localizations")
                        .HasForeignKey("ArticleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Peletnapechkai.Api.Domain.Content.MediaAsset", "CoverMediaAsset")
                        .WithMany()
                        .HasForeignKey("CoverMediaAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Peletnapechkai.Api.Domain.Localization.Locale", "Locale")
                        .WithMany("ArticleLocalizations")
                        .HasForeignKey("LocaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArticleGroup");

                    b.Navigation("CoverMediaAsset");

                    b.Navigation("Locale");
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Content.ArticleQualityChecklist", b =>
                {
                    b.HasOne("Peletnapechkai.Api.Domain.Content.ArticleLocalization", "Article")
                        .WithOne()
                        .HasForeignKey("Peletnapechkai.Api.Domain.Content.ArticleQualityChecklist", "ArticleLocalizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Content.ArticleRevision", b =>
                {
                    b.HasOne("Peletnapechkai.Api.Domain.Content.ArticleLocalization", "ArticleLocalization")
                        .WithMany("Revisions")
                        .HasForeignKey("ArticleLocalizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArticleLocalization");
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Content.Category", b =>
                {
                    b.HasOne("Peletnapechkai.Api.Domain.Localization.Locale", "Locale")
                        .WithMany()
                        .HasForeignKey("LocaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Locale");
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Content.EditorialComment", b =>
                {
                    b.HasOne("Peletnapechkai.Api.Domain.Content.ArticleLocalization", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleLocalizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Content.EditorialTask", b =>
                {
                    b.HasOne("Peletnapechkai.Api.Domain.Content.ArticleLocalization", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleLocalizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Content.HomepagePlacement", b =>
                {
                    b.HasOne("Peletnapechkai.Api.Domain.Content.ArticleLocalization", "ArticleLocalization")
                        .WithMany()
                        .HasForeignKey("ArticleLocalizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Peletnapechkai.Api.Domain.Localization.Locale", "Locale")
                        .WithMany()
                        .HasForeignKey("LocaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArticleLocalization");

                    b.Navigation("Locale");
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Content.SeoMetadata", b =>
                {
                    b.HasOne("Peletnapechkai.Api.Domain.Content.ArticleLocalization", "ArticleLocalization")
                        .WithOne("SeoMetadata")
                        .HasForeignKey("Peletnapechkai.Api.Domain.Content.SeoMetadata", "ArticleLocalizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArticleLocalization");
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Content.Tag", b =>
                {
                    b.HasOne("Peletnapechkai.Api.Domain.Localization.Locale", "Locale")
                        .WithMany()
                        .HasForeignKey("LocaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Locale");
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Knowledge.KnowledgeArticleLink", b =>
                {
                    b.HasOne("Peletnapechkai.Api.Domain.Content.ArticleLocalization", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleLocalizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Peletnapechkai.Api.Domain.Knowledge.KnowledgeCandidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("KnowledgeCandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Knowledge.KnowledgeCandidate", b =>
                {
                    b.HasOne("Peletnapechkai.Api.Domain.Localization.Locale", "Locale")
                        .WithMany()
                        .HasForeignKey("LocaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Locale");
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Localization.Locale", b =>
                {
                    b.HasOne("Peletnapechkai.Api.Domain.Localization.Region", "Region")
                        .WithMany("Locales")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Localization.LocaleCountry", b =>
                {
                    b.HasOne("Peletnapechkai.Api.Domain.Localization.Region", "Country")
                        .WithMany("LocaleCountries")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Peletnapechkai.Api.Domain.Localization.Locale", "Locale")
                        .WithMany("Countries")
                        .HasForeignKey("LocaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Locale");
                });

            modelBuilder.Entity("article_authors", b =>
                {
                    b.HasOne("Peletnapechkai.Api.Domain.Content.ArticleGroup", null)
                        .WithMany()
                        .HasForeignKey("article_group_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Peletnapechkai.Api.Domain.Content.Author", null)
                        .WithMany()
                        .HasForeignKey("author_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("article_categories", b =>
                {
                    b.HasOne("Peletnapechkai.Api.Domain.Content.ArticleLocalization", null)
                        .WithMany()
                        .HasForeignKey("article_localization_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Peletnapechkai.Api.Domain.Content.Category", null)
                        .WithMany()
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("article_media_assets", b =>
                {
                    b.HasOne("Peletnapechkai.Api.Domain.Content.ArticleGroup", null)
                        .WithMany()
                        .HasForeignKey("article_group_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Peletnapechkai.Api.Domain.Content.MediaAsset", null)
                        .WithMany()
                        .HasForeignKey("media_asset_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("article_sources", b =>
                {
                    b.HasOne("Peletnapechkai.Api.Domain.Content.ArticleGroup", null)
                        .WithMany()
                        .HasForeignKey("article_group_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Peletnapechkai.Api.Domain.Content.Source", null)
                        .WithMany()
                        .HasForeignKey("source_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("article_tags", b =>
                {
                    b.HasOne("Peletnapechkai.Api.Domain.Content.ArticleLocalization", null)
                        .WithMany()
                        .HasForeignKey("article_localization_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Peletnapechkai.Api.Domain.Content.Tag", null)
                        .WithMany()
                        .HasForeignKey("tag_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Content.ArticleGroup", b =>
                {
                    b.Navigation("Localizations");
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Content.ArticleLocalization", b =>
                {
                    b.Navigation("Revisions");

                    b.Navigation("SeoMetadata");
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Localization.Locale", b =>
                {
                    b.Navigation("ArticleLocalizations");

                    b.Navigation("Countries");
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Localization.Region", b =>
                {
                    b.Navigation("LocaleCountries");

                    b.Navigation("Locales");
                });
#pragma warning restore 612, 618
        }
    }
}
