// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Peletnapechkai.Api.Infrastructure.Persistence;

#nullable disable

namespace Peletnapechkai.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PublishingDbContext))]
    [Migration("20260804094846_InitialPublishingSchema")]
    partial class InitialPublishingSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Content.ArticleGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("article_groups", (string)null);
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Content.ArticleLocalization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArticleGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_group_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LocaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("locale_id");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<DateTimeOffset?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("SeoDescription")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("seo_description");

                    b.Property<string>("SeoTitle")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("seo_title");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ArticleGroupId", "LocaleId")
                        .IsUnique()
                        .HasDatabaseName("ux_article_localizations_group_locale");

                    b.HasIndex("LocaleId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_article_localizations_locale_slug");

                    b.HasIndex("LocaleId", "Status", "PublishedAt")
                        .HasDatabaseName("ix_article_localizations_publication");

                    b.ToTable("article_localizations", null, t =>
                        {
                            t.HasCheckConstraint("ck_article_localizations_slug_not_empty", "length(trim(slug)) > 0");

                            t.HasCheckConstraint("ck_article_localizations_title_not_empty", "length(trim(title)) > 0");
                        });
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Localization.Locale", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("language_code");

                    b.Property<string>("NativeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("native_name");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid")
                        .HasColumnName("region_id");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_locales_code");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasDatabaseName("ux_locales_single_default")
                        .HasFilter("is_default");

                    b.HasIndex("RegionId");

                    b.ToTable("locales", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0198f100-0000-7000-9000-000000000001"),
                            Code = "tr-TR",
                            DisplayName = "Turkish (Türkiye)",
                            IsDefault = true,
                            IsEnabled = true,
                            LanguageCode = "tr",
                            NativeName = "Türkçe (Türkiye)",
                            RegionId = new Guid("0198f100-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0198f100-0000-7000-9000-000000000002"),
                            Code = "en-US",
                            DisplayName = "English (United States)",
                            IsDefault = false,
                            IsEnabled = true,
                            LanguageCode = "en",
                            NativeName = "English (United States)",
                            RegionId = new Guid("0198f100-0000-7000-8000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("0198f100-0000-7000-9000-000000000003"),
                            Code = "de-DE",
                            DisplayName = "German (Germany)",
                            IsDefault = false,
                            IsEnabled = true,
                            LanguageCode = "de",
                            NativeName = "Deutsch (Deutschland)",
                            RegionId = new Guid("0198f100-0000-7000-8000-000000000003")
                        });
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Localization.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("code");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_regions_code");

                    b.ToTable("regions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0198f100-0000-7000-8000-000000000001"),
                            Code = "TR",
                            CurrencyCode = "TRY",
                            IsEnabled = true,
                            Name = "Türkiye"
                        },
                        new
                        {
                            Id = new Guid("0198f100-0000-7000-8000-000000000002"),
                            Code = "US",
                            CurrencyCode = "USD",
                            IsEnabled = true,
                            Name = "United States"
                        },
                        new
                        {
                            Id = new Guid("0198f100-0000-7000-8000-000000000003"),
                            Code = "DE",
                            CurrencyCode = "EUR",
                            IsEnabled = true,
                            Name = "Germany"
                        });
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Content.ArticleLocalization", b =>
                {
                    b.HasOne("Peletnapechkai.Api.Domain.Content.ArticleGroup", "ArticleGroup")
                        .WithMany("Localizations")
                        .HasForeignKey("ArticleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Peletnapechkai.Api.Domain.Localization.Locale", "Locale")
                        .WithMany("ArticleLocalizations")
                        .HasForeignKey("LocaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArticleGroup");

                    b.Navigation("Locale");
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Localization.Locale", b =>
                {
                    b.HasOne("Peletnapechkai.Api.Domain.Localization.Region", "Region")
                        .WithMany("Locales")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Content.ArticleGroup", b =>
                {
                    b.Navigation("Localizations");
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Localization.Locale", b =>
                {
                    b.Navigation("ArticleLocalizations");
                });

            modelBuilder.Entity("Peletnapechkai.Api.Domain.Localization.Region", b =>
                {
                    b.Navigation("Locales");
                });
#pragma warning restore 612, 618
        }
    }
}
